- hosts: remoteserver
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  
  - name: Add Docker apt repository key.
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - name: gather facts
    setup: 
  - name: Set the stable docker repository
    apt_repository: 
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      state: present
      update_cache: yes
  - name: Install Docker
    apt:
      name: docker-ce
      state: present
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: Pull an image
    docker_image:
      name: suvam14das/calculator-spe-devops
      
